

CREATE TABLE RESTAURANTS(ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY  ,NAME  VARCHAR(25) NOT NULL,LOCATION  VARCHAR(25) NOT NULL);

CREATE TABLE TESTRESTRATINGS(id int not null primary key AUTO_INCREMENT , RES_ID INT NOT NULL,
  AMBIENCE_RATING INT NOT NULL ,
FOOD_RATING INT NOT NULL ,
 SERVICE_RATING INT NOT NULL,comments varchar(100),username varchar(25),FOREIGN KEY(RES_ID) REFERENCES RESTAURANTS(ID))


INSERT INTO  RESTAURANTS(NAME,LOCATION) VALUES('BARBEQUEUE NATION','INDRANAGAR');	

INSERT INTO  RESTAURANTS(NAME,LOCATION) VALUES('PARADISE BIRYANI','INDRANAGAR');

INSERT INTO  RESTAURANTS(NAME,LOCATION) VALUES('PIZZA HUT','KORAMANGALA');

INSERT INTO  RESTAURANTS(NAME,LOCATION) VALUES('DOMINOS','KORAMANGALA');

INSERT INTO  RESTAURANTS(NAME,LOCATION) VALUES('BAKASUR','BELLANDUR');

INSERT INTO  RESTAURANTS(NAME,LOCATION) VALUES('BHAGINI','MARATHALLI');

INSERT INTO  RESTAURANTS(NAME,LOCATION) VALUES('NANDINI','KORAMANGALA');

INSERT INTO  RESTAURANTS(NAME,LOCATION) VALUES('MEGHANA','KORAMANGALA');	